---
services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # database initialisation for new instance
      - my-inventory-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  my-inventory-data:
