name: My Inventory Pipeline
on: push
env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{env.DB_USER}}"@"localhost" IDENTIFIED BY "${{env.DB_PASSWORD}}";' -uroot -proot
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}};' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Linting
        run: |
          go fmt ./...
          go vet ./...

      - name: Test
        run: |
          # Create .env var first
          touch .env

          pwd

          # Get path of env var
          export ENVPATH="${{github.workspace}}/.env"
          echo $ENVPATH 

          echo "DB_USER=${{env.DB_USER}}" >> .env
          echo "DB_NAME=${{env.DB_NAME}}" >> .env
          echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env

          go test ./...
